version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  websocket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8081:8081"
    depends_on:
      - postgres